[package]
name = "beancount"
version = "0.1.0"
edition = "2018"

[dependencies]
vercel_lambda = "*"
http = "0.1"
log = "0.4"
env_logger = "0.9.0"
parser = {version = "0.1.0", path = "../parser"}

[lib]
name = "beancount"
path = "beancount.rs"
