currency = "AUD"
[accounts]
cba = "Assets:MasterCard:CBA"
amex = "Liabilities:CreditCard:AMEX:Liang"
food = "Expenses:Food"
cash = "Assets:Cash"
savings = "Assets:Savings"
mark = "Expenses:Mark"
liang = "Expenses:Liang"
can = "Expenses:Can"
salary = "Income:Salary"
home = "Expenses:Home"
miscel = "Expenses:Miscellaneous"
visa = "Expenses:Visa"
receivable = "Assets:Receivable"
transport = "Expenses:Transport"
car = "Expenses:Car"
game = "Expenses:Game"
